### ISSUE TITLE
Sample description

### ISSUE THREAD

**Issue by hannespreishuber** [microsoftgraph/aspnetcore-webhook-with-resource-data-sample#6]
could be better
>>>Under Authorized application, select your app. (pro tip: enter the appid in the search box)

which search box?
this line is disabled in my dialog (lock symbol)

next hurdle
appsettings.jons relation to Azure portal
stuck with KEyvautlsettings- which azure portal dialog shows the fitting values (screenshot!)

**Comment by baywet** [comment]
Hey @hannespreishuber 
Thanks for the feedback and sorry about the late reply.
Do you have a screenshot of the locked searchbox?

**Comment by yagoodma** [comment]
![image](https://user-images.githubusercontent.com/30440290/78187459-188c4e80-7477-11ea-8de1-309997d57f28.png)

**Comment by baywet** [comment]
@yagoodma do you mind inserting this screenshot (also take it in black to match with the other ones) into our existing readme please?

**Comment by hannespreishuber** [comment]
I am lost with that, cause of long time... 
was some walkthrough with event hooks, 
stopped at 
Go to Access policies under Settings. Click Add Access Policy.
Under Secret Permissions, select Get and List.
Under Certificate Permissions, select Get and List.
Under Select principal, select your appid.
Under Authorized application, select your app. (pro tip: enter the appid in the search box)
Click Add to finish your access policy. Wait for your access policy to deploy.

but if this is the Screenshot. it doesnt help, What does the lock mean, how to unlock
where is the search box...

**Comment by baywet** [comment]
Oh I get where the confusion is coming from, you don't need to change anything under Authorized applications. This is for delegated access and this sample is using app only to access the key vault.
I'm not sure how the instruction got here at the first place, I authored PR #16 , can you have a look and confirm it clears the confusion before I merge it please?
